name: ig-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:

jobs:
  call-update_readme:
    uses: costateixeira/ig-badges/.github/workflows/add_badges.yaml@main    
  call_build: 
    uses: openhie/empty-fhir-ig/.github/workflows/main.yml@master
